test: supply additional code as Project rather than as Reference
fixes error CS1705: 'F0.Analyzers.Tests' uses 'System.Runtime' which has a higher version than referenced assembly 'System.Runtime'